### ISSUE TITLE
CakeChomps crashes on launch on Minecraft 1.14.2

### ISSUE THREAD

**Issue by Gavintime** [TheIllusiveC4/CakeChomps#1]
Versions:
* Minecraft 1.14.2
* Cake Chomps: 1.14-fabric-pre1
* Fabric API: 0.3.0+build.170
* Fabric: Mappings: 1.14.2+build.2
              Loader:      0.4.8+build.154

Observed Behavior:
Launching MInecraft with CakeChomps and FabricAPI causes a crash before the main window displays

Expected Behavior:
Game launches normally and we eat cake

Steps to Reproduce:
1. Setup a clean Minecraft 1.14.2 instance with the Fabric mod loader
2. Install CakeChomps and Fabric API
3. Launch Minecraft

Crash Log: https://pastebin.com/SA0CHtN9

**Comment by TheIllusiveC4** [comment]
This is due to the fact that Cake Chomps was only released for an early snapshot version of Fabric. It should be an easy fix, but I've got my hands busy with the Forge side of my mods right now and so I don't know when I'll be able to return to working on the Fabric side (though I do plan to do so eventually).

**Comment by Gavintime** [comment]
i noticed you have a separate repo for the fabric version of this mod, if i fork it and update it, is there a chance you would accept a pull request?

Edit: https://github.com/TheIllusiveC4/CakeChomps-Fabric/pull/1

**Comment by TheIllusiveC4** [comment]
Normally I would accept PRs of that nature, but in this case, I'd like to update it myself because there are some internal changes I'd like to make before releasing an update. Since you've put so much effort into this already, I'll expedite this and try my best to update sometime this weekend.

**Comment by Gavintime** [comment]
No worries, I mostly did it as self learning.

**Comment by TheIllusiveC4** [comment]
Closed in fe4e8bfcfb04e7500aa078b157130aa72762b387
